language: c
compiler:
 - clang
 - gcc
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq python3 pandoc re2c valgrind
script:
 - make testtarball
 - PROG=`ls cmark-*.*/build/src/cmark` make leakcheck
